ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../../config/environment', __FILE__)
require 'rails/test_help'
require 'mocha/mini_test'

class ActiveSupport::TestCase
  # Setup all fixtures in test/fixtures/*.yml for all tests in alphabetical order.
  fixtures :all

  # Add more helper methods to be used by all tests here...
  Aws.config[:dynamodb] = {
    stub_responses: {
      get_item: {
        item: {
          "category" => {
            "industry" => "Internet Software & Services",
            "industryGroup" => "Software & Services",
            "sector" => "Information Technology",
            "subIndustry" => "Internet"
          },
          "created_at" => 1461810349,
          "crunchbase" => {
            "handle" => "organization/google"
          },
          "description" => "Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for.",
          "domain" => "google.com",
          "domainAliases" => [
            "sparkbuy.com",
            "googleproductforums.com",
            "ojos-inc.com",
            "googlelabs.com",
            "appspotchat.com",
            "googl.com",
            "gogle.com",
            "riya.com",
            "gaccountmigration.com",
            "phonetic-arts.com",
            "picasa.com",
            "couturious.com",
            "covet.com",
            "greenparrotpictures.com",
            "google.jp",
            "remail.com",
            "postini.com",
            "postrank.com",
            "picnik.com",
            "talkbin.com",
            "picasa.net",
            "appliedsemantics.com",
            "googleadservices.com",
            "orkut.com",
            "industrial-perception.com",
            "gogole.com",
            "googlesyndication.com",
            "oingo.com",
            "psmtp.com",
            "google.hk",
            "googlestore.com",
            "google.kr",
            "google.in",
            "google.sg",
            "weardrobe.com",
            "writely.com",
            "google.com.cn",
            "google.com.ve",
            "google.co.hu",
            "google.ne.jp",
            "blogspot.co.id",
            "google.com.iq",
            "google.com.by",
            "google.co.je",
            "gmail.co",
            "perceptlabs.com",
            "duck.com",
            "gooogle.com",
            "google.co",
            "blogspot.pe",
            "blogspot.co.za",
            "goolge.com",
            "googel.com",
            "blogspot.rs",
            "docverse.com",
            "google.net",
            "omnisio.com",
            "blogspot.bg",
            "blogspot.qa",
            "googledrive.com",
            "google.io",
            "gmodules.com",
            "googletraveladservices.com",
            "blogspot.lt",
            "blogspot.si",
            "blogspot.am",
            "bitnik.com",
            "financialleadonline.com",
            "brokerbeater.co.uk",
            "appjet.com",
            "googleapps.com",
            "mygbiz.com",
            "blogspot.md",
            "google.us",
            "blogspot.lu",
            "blogspot.is",
            "wwwgoogle.com",
            "akwan.com.br",
            "phoneticarts.com",
            "pushlife.com",
            "brokerbeater.com",
            "g-mail.de",
            "gemail.com.br",
            "hotpot.com",
            "googlecommerce.com",
            "google.info",
            "like.co.uk",
            "culturalspot.org",
            "googlesource.com",
            "google.tk",
            "feedburner.com",
            "deja.com",
            "admob.com",
            "raterhub.com",
            "googleplex.com",
            "googlegroups.com",
            "jambool.com",
            "googlr.com",
            "wallet.com",
            "googleforwork.com",
            "blogger.com",
            "like.com",
            "gmail.com.br",
            "wildfireapps.com",
            "adsense.com",
            "gmail.de",
            "sprw.me",
            "quickoffice.com",
            "google-analytics.com",
            "googleanalytics.com",
            "measuremap.com",
            "boutiques.com",
            "blogspot.my",
            "blogspot.al",
            "blogspot.mk",
            "gmail.is",
            "photosphere.com",
            "wavesandbox.com",
            "blogspot.ba",
            "blogspot.co.ke",
            "gmail.co.in",
            "blogspot.hr",
            "googletagmanager.com",
            "blogspot.ug",
            "chrome.com",
            "goo.gl",
            "googlemail.com",
            "googlevideo.com",
            "picasaweb.com",
            "postinicorp.com",
            "socialdeck.com",
            "gmail.com.hk",
            "incentivetargeting.com",
            "channelintelligence.com",
            "froogle.com",
            "gmail.cm",
            "googlemaps.com",
            "recaptcha.net",
            "upoint.com",
            "quickofficeconnect.com",
            "google.fr"
          ],
          "emailProvider" => false,
          "facebook" => {
            "handle" => "google"
          },
          "foundedDate" => "1998-09-04",
          "geo" => {
            "city" => "Mountain View",
            "country" => "United States",
            "countryCode" => "US",
            "lat" => 37.4224497,
            "lng" => -122.0840329,
            "postalCode" => "94043",
            "state" => "California",
            "stateCode" => "CA",
            "streetName" => "Amphitheatre Parkway",
            "streetNumber" => "1600",
            "subPremise" => nil
          },
          "id" => "1d396c21-e421-4dd9-988e-55a8200c6e10",
          "legalName" => "Google Inc",
          "linkedin" => {
            "handle" => "company/google"
          },
          "location" => "1600 Amphitheatre Pkwy, Mountain View, CA 94043, USA",
          "logo" => "https://logo.clearbit.com/google.com",
          "metrics" => {
            "alexaGlobalRank" => 1,
            "alexaUsRank" => 1,
            "annualRevenue" => nil,
            "employees" => 79000,
            "googleRank" => 9,
            "marketCap" => 528860000000,
            "raised" => 25100000
          },
          "name" => "Google",
          "next_update_at" => Time.now.to_i + 7*24*60*60,
          "phone" => "+1 650-253-0000",
          "site" => {
            "emailAddresses" => [
              "dns-admin@google.com"
            ],
            "h1" => nil,
            "metaAuthor" => nil,
            "metaDescription" => "Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for.",
            "phoneNumbers" => [
              "+1 800-877-2981",
              "+1 866-588-1074",
              "+1 877-906-7957"
            ],
            "title" => "Google",
            "url" => "http://google.com"
          },
          "tags" => [
            "Internet",
            "Software",
            "Technology"
          ],
          "tech" => [
            "google_analytics",
            "double_click",
            "google_adwords",
            "google_apps"
          ],
          "ticker" => "GOOGL",
          "timeZone" => "America/Los_Angeles",
          "twitter" => {
            "avatar" => "https://pbs.twimg.com/profile_images/638751551457103872/KN-NzuRl_normal.png",
            "bio" => "News and updates from Google",
            "followers" => 14394322,
            "following" => 443,
            "handle" => "google",
            "id" => "20536157",
            "location" => "Mountain View, CA",
            "site" => "http://t.co/twxHxOtTvy"
          },
          "type" => "public",
          "url" => "https://www.google.com",
          "utcOffset" => -7
        }
      }
    }
  }
end
